version: "3.7"

services:
    vue-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        volumes:
            - .:/usr/src/app
        depends_on:
            - redis
        networks:
            - prova-pleno

    redis:
        image: redis:latest
        networks:
            - prova-pleno

networks:
    prova-pleno:
        driver: bridge